version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - API_KEY=your_secret_api_key_here
    depends_on:
      - redis
      - postgres
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: api_data
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
