name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: your_server_user
          SERVER_IP: your_server_ip
        run: |
          ssh -i $SSH_PRIVATE_KEY $SERVER_USER@$SERVER_IP << 'EOF'
            cd /path/to/your/api-rest-grafana
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF

